# Base configuration preset for StationWare

[net]
tickrate            = 30
max_connections     = 100

[game]
lobbyenabled        = true
lobbyduration       = 30
fallbackpreset      = "StationWare"
defaultpreset       = "StationWare"
soft_max_players    = 40
desc                = "A WarioWare-esque fork of Space Station 14, oriented on low-no roleplay and unbalanced fun."
map_rotation        = false

[infolinks]
bug_report          = "https://github.com/frigid14/stationware/issues/new/choose"
discord             = "https://discord.gg/TutAsX6JnY"
github              = "https://github.com/frigid14/stationware"
patreon             = "https://www.patreon.com/raincaldwell"

[rules]
time                = 15
rules_file          = "SW_Rules.txt"
rules_header        = "ui-rules-header-stationware"

[ooc]
enable_during_round = true

[tips]
enabled             = false # Re-enable when we have actual tips.

[vote]
preset_enabled      = false
map_enabled         = true

[shuttle]
cargo = false
emergency_enabled = false

[stationware] # Stationware cvars
total_challenges    = 15
